name: connection_check
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  internet_connection_checker_plus: ^1.0.1
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3

flutter:

  uses-material-design: true